"""Tests that all committed _pb2.py files were generated by protobuf >= 5.29."""

import re
from pathlib import Path

import pytest


_VERSION_HEADER_RE = re.compile(r"^# Protobuf Python Version:\s*(\d+)\.(\d+)", re.MULTILINE)
_VALIDATE_CALL_RE = re.compile(
    r"ValidateProtobufRuntimeVersion\s*\(\s*[^,]+,\s*(\d+)\s*,\s*(\d+)",
    re.DOTALL,
)

def _collect_pb2_files(repo_root: Path) -> list[Path]:
    return sorted((repo_root / "generated" / "python").rglob("*_pb2.py"))


def _pb2_header_version(path: Path) -> tuple[int, int] | None:
    """Return (major, minor) from the '# Protobuf Python Version:' header, or None."""
    header = path.read_text(encoding="utf-8", errors="replace")[:512]
    m = _VERSION_HEADER_RE.search(header)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


def _pb2_validate_call_version(path: Path) -> tuple[int, int] | None:
    """Return (major, minor) from the ValidateProtobufRuntimeVersion call, or None."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = _VALIDATE_CALL_RE.search(text)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


_REPO_ROOT = Path(__file__).parent.parent
_PB2_FILES = _collect_pb2_files(_REPO_ROOT)
_PROTO_FILES = sorted((_REPO_ROOT / "common").rglob("*.proto"))

# One-to-one guard: every .proto must produce exactly one _pb2.py.
# Also prevents silent empty-parametrize on a clean checkout.
assert len(_PB2_FILES) == len(_PROTO_FILES), (
    f"pb2 count ({len(_PB2_FILES)}) != proto count ({len(_PROTO_FILES)}). "
    "Either a proto is missing a pb2 (run 'make generate_python_protos') "
    "or a stale pb2 was left behind after a proto was deleted."
)


@pytest.mark.parametrize(
    "pb2_file",
    _PB2_FILES,
    ids=[str(f.relative_to(_REPO_ROOT)) for f in _PB2_FILES],
)
def test_pb2_header_version_at_least_5_29(pb2_file: Path):
    """Every committed _pb2.py must carry a 'Protobuf Python Version: >= 5.29' header.

    A file stamped < 5.29 was not regenerated with grpc_tools >= 1.69 and is stale.
    """
    version = _pb2_header_version(pb2_file)
    rel = pb2_file.relative_to(_REPO_ROOT)
    assert version is not None, (
        f"{rel}: missing 'Protobuf Python Version:' header — "
        "cannot verify the file was regenerated by the build-cleanup PR."
    )
    assert version >= (5, 29), (
        f"{rel}: header version is {version[0]}.{version[1]}, expected >= 5.29. "
        "Re-run 'make generate_python_protos' with grpc_tools >= 1.69 installed."
    )


@pytest.mark.parametrize(
    "pb2_file",
    _PB2_FILES,
    ids=[str(f.relative_to(_REPO_ROOT)) for f in _PB2_FILES],
)
def test_pb2_validate_call_version_at_least_5_29(pb2_file: Path):
    """ValidateProtobufRuntimeVersion call in each _pb2.py must assert >= (5, 29).

    This is the load-bearing runtime check — it actually breaks consumers importing
    a stale pb2 against a too-new runtime. The header comment is informational;
    this call is what enforces the version contract at import time.
    """
    version = _pb2_validate_call_version(pb2_file)
    rel = pb2_file.relative_to(_REPO_ROOT)
    assert version is not None, (
        f"{rel}: no ValidateProtobufRuntimeVersion call found — "
        "file may not be valid protobuf 5.x gencode."
    )
    assert version >= (5, 29), (
        f"{rel}: ValidateProtobufRuntimeVersion asserts ({version[0]}, {version[1]}), "
        "expected >= (5, 29). Re-run 'make generate_python_protos' with grpc_tools >= 1.69."
    )
