"""Tests that all committed _pb2.py files were generated by protobuf >= 5.29."""

import re
from pathlib import Path

import pytest


_VERSION_HEADER_RE = re.compile(r"^# Protobuf Python Version:\s*(\d+)\.(\d+)", re.MULTILINE)


def _collect_pb2_files(repo_root: Path) -> list[Path]:
    return sorted((repo_root / "generated" / "python").rglob("*_pb2.py"))


def _pb2_gencode_version(path: Path) -> tuple[int, int] | None:
    """Return (major, minor) from the 'Protobuf Python Version:' header, or None."""
    header = path.read_text(encoding="utf-8", errors="replace")[:512]
    m = _VERSION_HEADER_RE.search(header)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


_REPO_ROOT = Path(__file__).parent.parent
_PB2_FILES = _collect_pb2_files(_REPO_ROOT)


@pytest.mark.parametrize(
    "pb2_file",
    _PB2_FILES,
    ids=[str(f.relative_to(_REPO_ROOT)) for f in _PB2_FILES],
)
def test_pb2_gencode_version_at_least_5_29(pb2_file: Path):
    """Every committed _pb2.py must carry a 'Protobuf Python Version: >= 5.29' header.

    The build-cleanup PR regenerated all pb2 files using grpc_tools 1.69 (bundled
    protoc 29.0 / 5.29.x). A file stamped < 5.29 was not regenerated and is stale.
    """
    version = _pb2_gencode_version(pb2_file)
    rel = pb2_file.relative_to(_REPO_ROOT)
    assert version is not None, (
        f"{rel}: missing 'Protobuf Python Version:' header — "
        "cannot verify the file was regenerated by the build-cleanup PR."
    )
    assert version >= (5, 29), (
        f"{rel}: gencode version is {version[0]}.{version[1]}, expected >= 5.29. "
        "Re-run 'make generate_python_protos' with grpc_tools >= 1.69 installed."
    )
